### ISSUE TITLE
IllegalStateException: Must be called in the UI thread

### ISSUE THREAD

**Issue by Dichotomia** [pmd/pmd-eclipse-plugin#103]
![image](https://user-images.githubusercontent.com/5593198/58956332-5c062580-879e-11e9-9f1c-0228ffaa2e44.png)

**Comment by Dichotomia** [comment]
![image](https://user-images.githubusercontent.com/5593198/58956400-8bb52d80-879e-11e9-8816-34a302eae2a2.png)
java.lang.IllegalStateException: Must be called in the UI thread
	at net.sourceforge.pmd.eclipse.ui.priority.PriorityDescriptor.refreshImages(PriorityDescriptor.java:246)
	at net.sourceforge.pmd.eclipse.ui.priority.PriorityDescriptorCache.refreshImages(PriorityDescriptorCache.java:94)
	at net.sourceforge.pmd.eclipse.ui.priority.PriorityDescriptorCache.loadFromPreferences(PriorityDescriptorCache.java:50)
	at net.sourceforge.pmd.eclipse.ui.priority.PriorityDescriptorCache.<init>(PriorityDescriptorCache.java:28)
	at net.sourceforge.pmd.eclipse.ui.priority.PriorityDescriptorCache.<clinit>(PriorityDescriptorCache.java:24)
	at net.sourceforge.pmd.eclipse.ui.RuleLabelDecorator.decorate(RuleLabelDecorator.java:98)
	at org.eclipse.ui.internal.decorators.LightweightDecoratorDefinition.decorate(LightweightDecoratorDefinition.java:247)
	at org.eclipse.ui.internal.decorators.LightweightDecoratorManager$LightweightRunnable.run(LightweightDecoratorManager.java:105)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.ui.internal.decorators.LightweightDecoratorManager.decorate(LightweightDecoratorManager.java:360)
	at org.eclipse.ui.internal.decorators.LightweightDecoratorManager.getDecorations(LightweightDecoratorManager.java:346)
	at org.eclipse.ui.internal.decorators.DecorationScheduler$1.ensureResultCached(DecorationScheduler.java:333)
	at org.eclipse.ui.internal.decorators.DecorationScheduler$1.run(DecorationScheduler.java:300)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

**Comment by Dichotomia** [comment]
![image](https://user-images.githubusercontent.com/5593198/58956459-af787380-879e-11e9-9cfa-933af92084fd.png)
java.lang.ExceptionInInitializerError
	at net.sourceforge.pmd.eclipse.ui.RuleLabelDecorator.decorate(RuleLabelDecorator.java:98)
	at org.eclipse.ui.internal.decorators.LightweightDecoratorDefinition.decorate(LightweightDecoratorDefinition.java:247)
	at org.eclipse.ui.internal.decorators.LightweightDecoratorManager$LightweightRunnable.run(LightweightDecoratorManager.java:105)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.ui.internal.decorators.LightweightDecoratorManager.decorate(LightweightDecoratorManager.java:360)
	at org.eclipse.ui.internal.decorators.LightweightDecoratorManager.getDecorations(LightweightDecoratorManager.java:346)
	at org.eclipse.ui.internal.decorators.DecorationScheduler$1.ensureResultCached(DecorationScheduler.java:333)
	at org.eclipse.ui.internal.decorators.DecorationScheduler$1.run(DecorationScheduler.java:300)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.lang.IllegalStateException: Must be called in the UI thread
	at net.sourceforge.pmd.eclipse.ui.priority.PriorityDescriptor.refreshImages(PriorityDescriptor.java:246)
	at net.sourceforge.pmd.eclipse.ui.priority.PriorityDescriptorCache.refreshImages(PriorityDescriptorCache.java:94)
	at net.sourceforge.pmd.eclipse.ui.priority.PriorityDescriptorCache.loadFromPreferences(PriorityDescriptorCache.java:50)
	at net.sourceforge.pmd.eclipse.ui.priority.PriorityDescriptorCache.<init>(PriorityDescriptorCache.java:28)
	at net.sourceforge.pmd.eclipse.ui.priority.PriorityDescriptorCache.<clinit>(PriorityDescriptorCache.java:24)
	... 9 more

**Comment by adangel** [comment]
Thanks for the bug report!
Can you describe the steps (UI menus, actions) you did for this error to occur, so that I can reproduce it?

**Comment by adangel** [comment]
I could reproduce it. I first didn't see it, because I had the PMD Perspective opened directly after starting eclipse. This had the effect, that PMD and the PriorityDescriptors were successfully initialized before they are used in the RuleLabelDecorator. When starting in the Java perspective, the same exception occurred.

**Comment by adangel** [comment]
@Dichotomia I think, I've fixed the issue. Can try the new version?
It is available under this update site: https://dl.bintray.com/pmd/pmd-eclipse-plugin/snapshots/updates/
The version, which includes the fix is: 4.4.1.v20190607-1026

Thanks!

**Comment by Dichotomia** [comment]
It works.

Thanks !
