### ISSUE TITLE
Error executing command ReviewCode: java.util.regex.PatternSyntaxException: Illegal/unsupported escape sequence near index (part 2)

### ISSUE THREAD

**Issue by hbrands** [pmd/pmd-eclipse-plugin#159]
This is a follow-up issue from #150 which fixed not all problems in version 4.26.0.
I still observe log entries like the following:

```
2021/08/05 14:27:09.070 [Worker-3: ReviewCode] ERROR n.s.p.e.r.cmd.JobCommandProcessor - Error executing command ReviewCode: java.util.regex.PatternSyntaxException: Illegal/unsupported escape sequence near index 13
D:\workspace\gitlab\edrewemaster\edrewe-common\src\main\java\.*\*\.java
             ^
java.util.regex.PatternSyntaxException: Illegal/unsupported escape sequence near index 13
D:\workspace\gitlab\edrewemaster\edrewe-common\src\main\java\.*\*\.java
             ^
	at java.base/java.util.regex.Pattern.error(Pattern.java:2028)
	at java.base/java.util.regex.Pattern.escape(Pattern.java:2619)
	at java.base/java.util.regex.Pattern.atom(Pattern.java:2286)
	at java.base/java.util.regex.Pattern.sequence(Pattern.java:2210)
	at java.base/java.util.regex.Pattern.expr(Pattern.java:2069)
	at java.base/java.util.regex.Pattern.compile(Pattern.java:1783)
	at java.base/java.util.regex.Pattern.<init>(Pattern.java:1430)
	at java.base/java.util.regex.Pattern.compile(Pattern.java:1069)
	at net.sourceforge.pmd.eclipse.ui.actions.internal.InternalRuleSetUtil.convertStringPatterns(InternalRuleSetUtil.java:88)
	at net.sourceforge.pmd.eclipse.runtime.cmd.ReviewCodeCmd.filteredRuleSets(ReviewCodeCmd.java:674)
	at net.sourceforge.pmd.eclipse.runtime.cmd.ReviewCodeCmd.rulesetsFrom(ReviewCodeCmd.java:510)
	at net.sourceforge.pmd.eclipse.runtime.cmd.ReviewCodeCmd.determineFileExtensions(ReviewCodeCmd.java:305)
	at net.sourceforge.pmd.eclipse.runtime.cmd.ReviewCodeCmd.determineTotalWork(ReviewCodeCmd.java:275)
	at net.sourceforge.pmd.eclipse.runtime.cmd.ReviewCodeCmd.execute(ReviewCodeCmd.java:181)
	at net.sourceforge.pmd.eclipse.runtime.cmd.JobCommandProcessor$1.run(JobCommandProcessor.java:60)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

I think you can reproduce this remaining issue with my provided example project from issue #150 if you extract it on Windows in a dir like "D:\workspace\gitlab" and import it as an existing project into an Eclipse workspace. It seems to me that the backsplash in the root path is not escaped for the regex, so "\g" is not recognized by Pattern#compile (whereas "\w" and "\e" is interpreted by Pattern#compile). Hope this helps.

**Comment by adangel** [comment]
Hi @hbrands , I've just pushed a fix for the bug. Could you test the latest snapshot, whether it really fixes your problem?
You can install the latest snapshot from here: https://pmd.github.io/pmd-eclipse-plugin-p2-site/snapshot/
Thanks!

**Comment by adangel** [comment]
Thanks for testing! The new version is out since a couple of days -> https://github.com/pmd/pmd-eclipse-plugin/releases/tag/4.27.0.v20210828-1623-r
