### ISSUE TITLE
Processing errors without cause

### ISSUE THREAD

**Issue by MCMicS** [pmd/pmd-eclipse-plugin#29]
If I run the ruleset within Eclipse, the PMD log file shows errors. But I don't see what is the problem. Try clear old violation and re-Check.

```
2017/09/11 09:50:45,400 INFO  PMDBuilder                       Incremental builder activated
2017/09/11 09:50:45,402 INFO  PMDBuilder                       Build done.
2017/09/11 09:50:45,402 INFO  ReviewCodeCmd                    ReviewCode command starting.
2017/09/11 09:50:45,408 INFO  ReviewCodeCmd                    Processing marker directives
2017/09/11 09:50:45,472 INFO  ReviewCodeCmd                    End of processing marker directives. 0 violations for 1 files.
2017/09/11 09:50:45,473 ERROR BaseVisitor                      PMD exception visiting Class3.class
net.sourceforge.pmd.PMDException: There were processing errors!

	at net.sourceforge.pmd.eclipse.runtime.cmd.BaseVisitor.reviewResource(BaseVisitor.java:367)
	at net.sourceforge.pmd.eclipse.runtime.cmd.DeltaVisitor.visitAdded(DeltaVisitor.java:66)
	at net.sourceforge.pmd.eclipse.runtime.cmd.DeltaVisitor.visit(DeltaVisitor.java:45)
	at org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:64)
	at org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:75)
	at org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:75)
	at org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:75)
	at org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:75)
	at org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:75)
	at org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:75)
	at org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:75)
	at org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:75)
	at org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:75)
	at org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:75)
	at org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:75)
	at org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:75)
	at org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:48)
	at net.sourceforge.pmd.eclipse.runtime.cmd.ReviewCodeCmd.processResourceDelta(ReviewCodeCmd.java:569)
	at net.sourceforge.pmd.eclipse.runtime.cmd.ReviewCodeCmd.execute(ReviewCodeCmd.java:189)
	at net.sourceforge.pmd.eclipse.runtime.cmd.JobCommandProcessor$1.run(JobCommandProcessor.java:90)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)
```

another with ALL Log:
```
2017/09/11 10:02:35,398 INFO  ReviewCodeCmd                    ReviewCode command has ended.
2017/09/11 10:02:35,398 DEBUG DeltaVisitor                     Visiting added resource queue
2017/09/11 10:02:35,398 DEBUG DeltaVisitor                     Visiting added resource package-info.class
2017/09/11 10:02:35,398 DEBUG BaseVisitor                      Derived files included: false
2017/09/11 10:02:35,398 DEBUG BaseVisitor                      file package-info.class is derived: false
2017/09/11 10:02:35,398 DEBUG BaseVisitor                      file checked: true
2017/09/11 10:02:35,398 DEBUG BaseVisitor                      discovered language: LanguageModule:PHP: Hypertext Preprocessor(PhpLanguageModule)+version:
2017/09/11 10:02:35,405 DEBUG BaseVisitor                      PMD running on file package-info.class
2017/09/11 10:02:35,406 DEBUG BaseVisitor                      PMD run finished.
2017/09/11 10:02:35,406 DEBUG BaseVisitor                      PMD found 0 violations for file package-info.class
2017/09/11 10:02:35,418 ERROR BaseVisitor                      PMD exception visiting package-info.class
net.sourceforge.pmd.PMDException: There were processing errors!
	at net.sourceforge.pmd.eclipse.runtime.cmd.BaseVisitor.reviewResource(BaseVisitor.java:367)
	at net.sourceforge.pmd.eclipse.runtime.cmd.DeltaVisitor.visitAdded(DeltaVisitor.java:66)
	at net.sourceforge.pmd.eclipse.runtime.cmd.DeltaVisitor.visit(DeltaVisitor.java:45)
	at org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:64)
```

**Comment by MCMicS** [comment]
I see that the plug-in detect the wrong language:
> discovered language: LanguageModule:PHP
`Visiting changed resource IllegalExceptionTest.class
2017/09/11 10:08:06,067 DEBUG BaseVisitor                      Derived files included: false
2017/09/11 10:08:06,067 DEBUG BaseVisitor                      file IllegalExceptionTest.class is derived: false
2017/09/11 10:08:06,067 DEBUG BaseVisitor                      file checked: true
2017/09/11 10:08:06,067 DEBUG BaseVisitor                      discovered language: LanguageModule:PHP: Hypertext Preprocessor(PhpLanguageModule)+version:
2017/09/11 10:08:06,071 DEBUG BaseVisitor                      PMD running on file IllegalExceptionTest.class
2017/09/11 10:08:06,072 DEBUG BaseVisitor                      PMD run finished.
2017/09/11 10:08:06,072 DEBUG BaseVisitor                      PMD found 0 violations for file IllegalExceptionTest.class
2017/09/11 10:08:06,088 ERROR BaseVisitor                      PMD exception visiting IllegalExceptionTest.class`

How can I force a language?

**Comment by MCMicS** [comment]
This error occurs also if I use file filter:
![grafik](https://user-images.githubusercontent.com/4604206/30266363-6a82c1b0-96df-11e7-8b3e-de23d4bb1153.png)

**Comment by MCMicS** [comment]
But why was wrong language detected?
PHP for java file:

>  DEBUG BaseVisitor discovered language: LanguageModule:PHP: Hypertext Preprocessor(PhpLanguageModule)+version

**Comment by adangel** [comment]
The language is determined by the file extension. PHP as registered ".php" and ".class". 
However, for PHP only the Copy-Paste-Detection is supported - so the pmd plugin should not even try to use PMD on PHP files... Could you open a new issue for that? Thanks!
