### ISSUE TITLE
Runtime Exception when loading stored ruleset file. Falling back to default ruleset.Unable to find referenced rule UseSingleton; perhaps the rule name is mispelled?

### ISSUE THREAD

**Issue by MCMicS** [pmd/pmd-eclipse-plugin#6]
With Plugin: 4.0.6.v20150401-1945 I got every restart following error.
Runtime Exception when loading stored ruleset file. Falling back to default ruleset.Unable to find referenced rule UseSingleton; perhaps the rule name is mispelled?

java.lang.IllegalArgumentException: Unable to find referenced rule UseSingleton; perhaps the rule name is mispelled?
	at net.sourceforge.pmd.RuleSetFactory.parseRuleReferenceNode(RuleSetFactory.java:517)
	at net.sourceforge.pmd.RuleSetFactory.parseRuleNode(RuleSetFactory.java:293)
	at net.sourceforge.pmd.RuleSetFactory.parseRuleSetNode(RuleSetFactory.java:242)
	at net.sourceforge.pmd.RuleSetFactory.createRuleSet(RuleSetFactory.java:176)
	at net.sourceforge.pmd.RuleSetFactory.createRuleSet(RuleSetFactory.java:171)
	at net.sourceforge.pmd.RuleSetFactory.createRuleSet(RuleSetFactory.java:158)
	at net.sourceforge.pmd.eclipse.runtime.preferences.impl.PreferencesManagerImpl.getRuleSetFromStateLocation(PreferencesManagerImpl.java:455)
	at net.sourceforge.pmd.eclipse.runtime.preferences.impl.PreferencesManagerImpl.getRuleSet(PreferencesManagerImpl.java:250)
	at net.sourceforge.pmd.eclipse.runtime.properties.impl.ProjectPropertiesImpl.<init>(ProjectPropertiesImpl.java:99)
	at net.sourceforge.pmd.eclipse.runtime.properties.impl.PropertiesFactoryImpl.newProjectProperties(PropertiesFactoryImpl.java:70)
	at net.sourceforge.pmd.eclipse.runtime.properties.impl.ProjectPropertiesManagerImpl.loadProjectProperties(ProjectPropertiesManagerImpl.java:100)
	at net.sourceforge.pmd.eclipse.plugin.PMDPlugin.loadProjectProperties(PMDPlugin.java:407)
	at net.sourceforge.pmd.eclipse.runtime.cmd.ReviewCodeCmd.getProjectProperties(ReviewCodeCmd.java:361)
	at net.sourceforge.pmd.eclipse.runtime.cmd.ReviewCodeCmd.processResourceDelta(ReviewCodeCmd.java:516)
	at net.sourceforge.pmd.eclipse.runtime.cmd.ReviewCodeCmd.execute(ReviewCodeCmd.java:183)
	at net.sourceforge.pmd.eclipse.runtime.cmd.JobCommandProcessor$1.run(JobCommandProcessor.java:90)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)

**Comment by MCMicS** [comment]
move to sourceforge issues
