### ISSUE TITLE
Problems with trying to extend a rule class for PMD eclipse plugin: PMD can't find the rule implementation class

### ISSUE THREAD

**Issue by inondle** [pmd/pmd-eclipse-plugin#8]
I'm trying to make a custom rule to be run for the eclipse plugin version of PMD. I have my implementation class extending an abstractJavaRule and have configured a ruleset xml file. The project is a plugin fragment and has it's host set as the pmd plugin. The issue is that when I try to run my fragment as an "eclipse application" I can't seem to add the custom rule to PMD's list of rules. 

The procedure I'm doing is to go to preferences > PMD > rule configuration and attempt to import a ruleset, then select the ruleset XML file. The console gives me this error code: 

```
java.lang.RuntimeException: Couldn't find the class archnemesis-pmd-rule.src.rule.ArchitectureComplianceCheck cannot be found by net.sourceforge.pmd.eclipse.plugin_4.0.7.v20150522-1709
at net.sourceforge.pmd.RuleSetFactory.classNotFoundProblem(RuleSetFactory.java:270)
at net.sourceforge.pmd.RuleSetFactory.parseRuleSetNode(RuleSetFactory.java:252)
at net.sourceforge.pmd.RuleSetFactory.createRuleSet(RuleSetFactory.java:176)
at net.sourceforge.pmd.RuleSetFactory.createRuleSet(RuleSetFactory.java:171)
at net.sourceforge.pmd.RuleSetFactory.createRuleSets(RuleSetFactory.java:135)
at net.sourceforge.pmd.RuleSetFactory.createRuleSets(RuleSetFactory.java:119)
at net.sourceforge.pmd.eclipse.ui.preferences.RuleSetSelectionDialog.selectedRuleset(RuleSetSelectionDialog.java:429)
at net.sourceforge.pmd.eclipse.ui.preferences.RuleSetSelectionDialog.updateRuleTable(RuleSetSelectionDialog.java:387)
at net.sourceforge.pmd.eclipse.ui.preferences.RuleSetSelectionDialog.ruleSetChanged(RuleSetSelectionDialog.java:325)
at net.sourceforge.pmd.eclipse.ui.preferences.RuleSetSelectionDialog.access$3(RuleSetSelectionDialog.java:324)
at net.sourceforge.pmd.eclipse.ui.preferences.RuleSetSelectionDialog$5.widgetSelected(RuleSetSelectionDialog.java:284)
... this is where the net.sourceforge errors end.
```

**Comment by adangel** [comment]
I guess, you asked the same question here: https://sourceforge.net/p/pmd/discussion/188193/thread/ebce1f0d/
so, I'll answer that over there....
